project:
  type: website
  output-dir: docs  # Ensure Quarto builds into /docs for GitHub Pages

website:
  title: "We, The People"
  navbar:
    left:
      - href: pages/issues.qmd
        text: Major Issues
      - href: pages/action.qmd
        text: Take Action
      - href: pages/resources.qmd
        text: Resources
    right:
      - icon: github
        href: "https://github.com/laurenchenarides/wethepeople"
        aria-label: "GitHub Repository"
  page-footer: "Powered by Quarto | Fork on GitHub"

format:
  html:
    theme: cosmo
    toc: true
    highlight-style: github  # Ensures code blocks are formatted properly

editor: visual

execute:
  freeze: auto  # Avoids unnecessary re-execution

metadata-files:
  - _extensions.yml  # Optional: Ensures Quarto extensions are recognized