project:
  type: website
  output-dir: docs  # Ensure Quarto builds into /docs for GitHub Pages

website:
  title: "wethepeople"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/issues.qmd
        text: Major Issues
      - href: pages/action.qmd
        text: Take Action
      - href: pages/resources.qmd
        text: Resources
  page-footer: "Powered by Quarto | Fork on GitHub"
      - icon: github
        href: "https://github.com/laurenchenarides/wethepeople"
        aria-label: "GitHub Repository"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

